spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:ohwaiter
    driverClassName: org.h2.Driver
    password: '123'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
server:
  error:
    include-message: always